### ISSUE TITLE
Using the oss-maven-central profile deploys to the same repository twice

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-community-hub/community-hub-release-parent#17]
## Description

As far as I understood this pom file allows users to easily deploy to two repositories at once. This is also what is described in the README

> This is a POM which can be inherited for [Community Hub Maven releases](https://github.com/camunda-community-hub/community-action-maven-release), defining some common release properties. It allows deploying to two repositories simultaneously. One is a Nexus OSS server, the other one a Nexus Enterprise server. It will deploy the artifacts at the end of the build to keep the window of failure small when talking to external systems.

This is not what happens currently. Triggering a deployment with the `oss-maven-central` profile will deploy twice to the Nexus OSS server. The POM file contains a comment saying:

> the execution default-deploy (defined in camunda-release-parent) deploys into camunda nexus
>  add additional execution to deploy to maven central

This is false. The `default-deploy` defined in `camunda-release-parent` does trigger a deployment. However, it is done to the Nexus OSS server instead of the Camunda Nexus.
The additional execution to deploy to Maven Central will do the same deployment a second time (albeit with slightly different configurations).

## Why does this happen?

My best guess is that this is happening because of the `distributionManagement` that is defined in the `oss-maven-central` profile. I am not entirely sure how this is used by the `nexus-staging-maven-plugin`, however the fact that it is defined here means that it will override the `distributionManagement` that is defined in the `camunda-release-parent`. I did a dry-run of my own project where I removed the `distributionManagement` from this POM and this resolved this issue. I don't know if this works in all cases, so I'm hesitant to make a PR that changes this.

## Community Release Action 
The community release action works around this issue by doing two deployments:

```
        test -z "${{ inputs.release-version }}" && echo "::debug::Skipping Release because release-version is unset" && exit 0
        echo "Set version to ${{ inputs.release-version }}"
        mvn -B ${{ inputs.maven-additional-options }} versions:set org.codehaus.mojo:versions-maven-plugin:2.8.1:update-child-modules -DnewVersion=${{ inputs.release-version }}
        echo "Deploy release to Camunda Repository using ${{inputs.release-profile}} profile"
        mvn -B ${RELEASE_PROFILE} ${{ inputs.maven-additional-options }} -DskipTests ${{ inputs.maven-release-options }} deploy
        echo "Deply release to Maven Central using profiles ${{inputs.release-profile}}, ${{inputs.central-release-profile}}"
        mvn -B ${RELEASE_PROFILE} ${CENTRAL_RELEASE_PROFILE} ${{ inputs.maven-additional-options }} -DskipTests -DnexusUrl=https://${{inputs.maven-url}}/  ${{ inputs.maven-release-options }} deploy
```

The first one will only use the `community-action-maven-release` profile, which does not override the `distributionManagement` and deploys to the Camunda Nexus. The seconds deployment uses both the `community-action-maven-release` and the `oss-maven-central` profile, which does override the `distributionManagement`. This seconds deploy command will deploy to Maven Central 2 times.

When this bug is fixed I believe we should also modify the community maven release action to only perform 1 deploy command.

**Comment by berndruecker** [comment]
Maybe we can do this together with https://github.com/camunda-community-hub/community-action-maven-release/issues/48. @remcowesterhoud Did you follow up any more on this by chance?

**Comment by remcowesterhoud** [comment]
Except for analysing and creating this issue I didn't take any further action.

**Comment by berndruecker** [comment]
OK - looking into this now. I would also tackle https://github.com/camunda-community-hub/community-hub-release-parent/issues/9 alongside with it

**Comment by zambrovski** [comment]
Before solving this, let me check if I understand the requirement correctly:

__A library using community-hub-parent and community-action should be able to run a release and publish the artifact into Nexus-OSS and into Camunda Artifactory.__

If this statement is true, I would like to state, that there is no way in Maven to release one artifact in to two repositories by a single run. This is the reason for creating profiles, because EVERY release plugin (maven-deploy-plugin, nexus-staging-plugin) consider the use of the `distributionManagement` and this can point only to one repository at a given point of time.

For this reason, there is no other way to publish to two repositories without the usage of profiles. In the same time, I believe it is much clearer if both publications are performed from dedicated profiles. By doing so, We could shift the entire profile configuration of the Artifactory publication into corresponding profile and the same can be done for Nexus publication. If you are generally agree with this approach, I would make a PR demonstrating this issue. 

As @berndruecker said, we should generally do thi after #9 is solved, since we otherwise inherit a lot of stuff from the `camunda-parent` which has nothing to do with the Camunda HUB.

**Comment by zambrovski** [comment]
I fixed the parent and the action and the artifacts are now released into two repositories (camunda artifactory and oss nexus).

Let's release the parent with the newest changes.

**Comment by berndruecker** [comment]
Actually, I could do a release using the 1.4.0-SNAPSHOT parent correctly: https://github.com/camunda-community-hub/community-hub-extension-example/actions/runs/4062895558/jobs/6994482279. This is awesome - thank you @zambrovski! I will close the issue and do a release of the parent later today.
